name: Push
concurrency:
  group: push
on:
  push:
    branches:
      - master
      - beta
      - alpha
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      HUSKY: 0
      GITHUB_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      NPM_CONFIG_PROVENANCE: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org/'
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build
        working-directory: packages/lib

      # Latest version of npm needed for provenance
      - name: Install latest npm
        run: npm install -g npm@latest

      - name: replace workspace refs in yarn.lock
        run: |
          # Replace all workspace references in yarn.lock
          sed -i 's/react-native-maps@workspace:packages\/lib/react-native-maps@npm:1.22.6/g' yarn.lock
          sed -i 's/react-native-maps@workspace:\*/react-native-maps@npm:1.22.6/g' yarn.lock
          sed -i 's/react-native-maps: "workspace:packages\/lib"/react-native-maps: "1.22.6"/g' yarn.lock
          sed -i 's/workspace:\*/*/' yarn.lock

          # Print the modified yarn.lock for verification
          echo "=== Modified yarn.lock (excerpt) ==="
          grep -A 5 "react-native-maps" yarn.lock || echo "No matching lines found"

          # Replace workspace reference in example's package.json
          sed -i 's/"react-native-maps": "workspace:packages/lib"/"react-native-maps": "1.22.6"/g' packages/example/package.json

          # Print the modified package.json for verification
          echo "=== Modified packages/example/package.json (excerpt) ==="
          grep -A 3 -B 3 "react-native-maps" packages/example/package.json || echo "No matching lines found"

      - name: Show complete files for verification
        run: |
          echo "=== Complete yarn.lock ==="
          cat yarn.lock

          echo "=== Complete example/package.json ==="
          cat packages/example/package.json

      - name: Release
        run: yarn release
        working-directory: packages/lib
