name: Push
concurrency:
  group: push
on:
  push:
    branches:
      - master
      - beta
      - alpha
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      HUSKY: 0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org/'
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build
        working-directory: packages/lib

      # Latest version of npm needed for provenance
      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Configure .npmrc with auth token
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
          echo "package-lock=false" >> .npmrc
        working-directory: packages/lib
        env:
          GITHUB_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true

      - name: Release
        run: npx semantic-release --ci --debug
        working-directory: packages/lib
        env:
          GITHUB_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
