name: Push
concurrency:
  group: push
on:
  push:
    branches:
      - master
      - beta
      - alpha
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      HUSKY: 0
      GITHUB_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      NPM_CONFIG_PROVENANCE: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org/'
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build
        working-directory: packages/lib

      # Latest version of npm needed for provenance
      - name: Install latest npm
        run: npm install -g npm@latest

      - name: remove workspace ref from yarn.lock
        run: sed -i 's/"workspace:\*"/"*"/g' yarn.lock

      - name: Release
        run: yarn release
        working-directory: packages/lib
